#!/usr/bin/env bash

# Thanks to oatman (NoBoilerPlate on Youtube for this script)

set -e

pushd ~/.setup/nixos/ &>/dev/null

alejandra . &>/dev/null \
  || ( alejandra . ; echo "formatting failed!" && exit 1)

if git diff --quiet "*.nix"; then
    echo "No changes detected, exiting."
    popd &>/dev/null
    exit 0
fi

git diff -U0 '*.nix'

echo "NixOS Rebuilding ..."

sudo nixos-rebuild switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
rm nixos-switch.log

current=$(nixos-rebuild list-generations | grep current)

git commit -am "$current"

popd &> /dev/null

notify-send -e "NixOS system was rebuilt!" --icon=software-update-available
